# Run tests

name: Automated tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2.3.4

      - name: Setup java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8


      - name: Run tests
        run: ./gradlew check
